id: I43C8425F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T09:09:23+00:00'
last_modified: '2022-06-08T08:51:31.097545+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN7654
  title: དབུ་ཚབས་དྲི་མ་འཇིགས་སྐྱོབ་སྟེང་ཕྱོགས་ནམ་མཁའི་བླ་བྲེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    254B:
      image_group_id: I3CN7656
      title: ''
      total_pages: 339
      order: 1
      base_file: 254B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
